# Generated by Django 5.1.6 on 2025-02-16 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('cultural', 'Cultural'), ('relajacion', 'Relajación'), ('aventura', 'Aventura'), ('otros', 'Otros')], max_length=10)),
                ('ubicacion', models.CharField(max_length=255)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
