# Generated by Django 5.1.5 on 2025-02-17 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_experiencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencia',
            name='administrador',
        ),
        migrations.RemoveField(
            model_name='experiencia',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='experiencia',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='experiencia',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='experiencia',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='experiencia',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='experiencia',
            name='nombre',
            field=models.CharField(default='sin nombre', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL)),
                ('experiencias', models.ManyToManyField(related_name='actividades', to='users.experiencia')),
            ],
        ),
    ]
